### ISSUE TITLE
Imprecision in the documentation

### ISSUE THREAD

**Issue by themage** [dmanto/Mojolicious-Plugin-Cron#10]
Hi,

I think you have a few small imprecisions in the documentation about when crons runs, specifically when referring to range and wildcards:

* '*/5 9-17 * * *' - you say it runs every 5 minutes from 9 to 5. It actually runs every 5 minutes from 9:00 to 17:55.
* '*/10 15 * * *' - you say it runs every 10th minute past 15 hours, but it really runs every 10 minutes between 15:00 and 15:59 (15:50, in practice). A cron to run every day at 15:10 would be '10 15 * * *'
* '*/15 15 * * *' - same as the previous one, but every 15 minutes. A cron to run every day at 15:15 would be '15 15 * * *'.

Cheers

**Comment by dmanto** [comment]
Hi themage, and thanks for your comments,

These time related english expression will always be a mistery to me (english is not my native language, as you may have noticed).

So I used a web page called "crontab guru" [https://crontab.guru](https://crontab.guru), and changed the results a little to fit in each sentence.

For instance, "*/10 15 * * *" in spanish would probably be "cada 10 minutos a la hora 15", but when I look at the mentioned web page I get "At every 10th minute past hour 15". To me that sentence doesn't sound right, because "past hour 15" seems to refer to following hours also, but I stick to the guru page, and nobody complained, so far :)

Anyway, if you could submit a PR with a better / clearer wording I will be gratefull :)

BR,
